# Generated by Django 2.1b1 on 2018-07-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_fav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='genric',
            new_name='genre',
        ),
    ]
